const accordionContent = [
  [ {'title': 'Mauro Bianchi', 'content': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nisl justo, feugiat vitae tempus aliquet, elementum id felis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Quisque id iaculis sem. Nam libero dui, posuere eget lacus id, bibendum facilisis arcu. Pellentesque ac viverra massa, at luctus urna. Phasellus mi sapien, fermentum in luctus vel, ultricies eu nisi. Proin sodales ex orci, luctus venenatis ligula malesuada non. Phasellus semper ornare scelerisque. Aenean a turpis tellus. Nam ut sapien ac turpis rhoncus ultrices. Donec ullamcorper ex molestie sapien viverra tempor.<br /><br />Etiam commodo facilisis magna eu rutrum. Mauris a rhoncus elit. Quisque ullamcorper convallis arcu, quis semper nibh pulvinar a. Sed non rhoncus augue. Vivamus ex nisl, efficitur eget odio a, vehicula viverra ligula. Sed mattis mollis vulputate. Donec faucibus sit amet elit consectetur bibendum. Cras eu accumsan purus. Morbi suscipit blandit lacinia. Interdum et malesuada fames ac ante ipsum primis in faucibus.'} ],
  [ {'title': 'Paolo Rossi', 'content': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nisl justo, feugiat vitae tempus aliquet, elementum id felis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Quisque id iaculis sem. Nam libero dui, posuere eget lacus id, bibendum facilisis arcu. Pellentesque ac viverra massa, at luctus urna. Phasellus mi sapien, fermentum in luctus vel, ultricies eu nisi. Proin sodales ex orci, luctus venenatis ligula malesuada non. Phasellus semper ornare scelerisque. Aenean a turpis tellus. Nam ut sapien ac turpis rhoncus ultrices. Donec ullamcorper ex molestie sapien viverra tempor.<br /><br />Etiam commodo facilisis magna eu rutrum. Mauris a rhoncus elit. Quisque ullamcorper convallis arcu, quis semper nibh pulvinar a. Sed non rhoncus augue. Vivamus ex nisl, efficitur eget odio a, vehicula viverra ligula. Sed mattis mollis vulputate. Donec faucibus sit amet elit consectetur bibendum. Cras eu accumsan purus. Morbi suscipit blandit lacinia. Interdum et malesuada fames ac ante ipsum primis in faucibus.'} ],
  [ {'title': 'Maria Verdi', 'content': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nisl justo, feugiat vitae tempus aliquet, elementum id felis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Quisque id iaculis sem. Nam libero dui, posuere eget lacus id, bibendum facilisis arcu. Pellentesque ac viverra massa, at luctus urna. Phasellus mi sapien, fermentum in luctus vel, ultricies eu nisi. Proin sodales ex orci, luctus venenatis ligula malesuada non. Phasellus semper ornare scelerisque. Aenean a turpis tellus. Nam ut sapien ac turpis rhoncus ultrices. Donec ullamcorper ex molestie sapien viverra tempor.<br /><br />Etiam commodo facilisis magna eu rutrum. Mauris a rhoncus elit. Quisque ullamcorper convallis arcu, quis semper nibh pulvinar a. Sed non rhoncus augue. Vivamus ex nisl, efficitur eget odio a, vehicula viverra ligula. Sed mattis mollis vulputate. Donec faucibus sit amet elit consectetur bibendum. Cras eu accumsan purus. Morbi suscipit blandit lacinia. Interdum et malesuada fames ac ante ipsum primis in faucibus.'} ],
  [ {'title': 'Annalisa Rossetti', 'content': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nisl justo, feugiat vitae tempus aliquet, elementum id felis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Quisque id iaculis sem. Nam libero dui, posuere eget lacus id, bibendum facilisis arcu. Pellentesque ac viverra massa, at luctus urna. Phasellus mi sapien, fermentum in luctus vel, ultricies eu nisi. Proin sodales ex orci, luctus venenatis ligula malesuada non. Phasellus semper ornare scelerisque. Aenean a turpis tellus. Nam ut sapien ac turpis rhoncus ultrices. Donec ullamcorper ex molestie sapien viverra tempor.<br /><br />Etiam commodo facilisis magna eu rutrum. Mauris a rhoncus elit. Quisque ullamcorper convallis arcu, quis semper nibh pulvinar a. Sed non rhoncus augue. Vivamus ex nisl, efficitur eget odio a, vehicula viverra ligula. Sed mattis mollis vulputate. Donec faucibus sit amet elit consectetur bibendum. Cras eu accumsan purus. Morbi suscipit blandit lacinia. Interdum et malesuada fames ac ante ipsum primis in faucibus.'} ],
];

console.log(accordionContent[0][0].title);

const accordionButton = document.querySelectorAll(".accordion-button");
const accordionBody = document.querySelectorAll(".accordion-body");

function fillAccordion() {
  for (let i=0; i<accordionContent.length; i++) {
    accordionButton[i].innerHTML = accordionContent[i][0].title;
    accordionBody[i].innerHTML = accordionContent[i][0].content;
  }
}

fillAccordion();